Name: libft.a

Files: ft_isalpha.c\
 		ft_strchr.c\
		ft_tolower.c\
		ft_isascii.c\
		ft_memcmp.c\
		ft_strncmp.c\
		ft_toupper.c\
		ft_atoi.c\
		ft_isdigit\.c\
		ft_memcpy.c\
		ft_strlcat.c\
		ft_bzero.c\
		ft_isprint.\c\
		ft_memmove.c\
		ft_strlcpy.c\
		ft_strnstr.c\
		ft_isalnum.c\
		ft_memchr.c\
		ft_memset.c\
		ft_strlen.c\
		ft_strrchr.c

OBJS: $(Files:.c=.0)
CC = cc
CFlags = -Wall -Werror -Wextra

.c.o: